# 模组元数据（TOML）：https://github.com/toml-lang/toml
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "reverie_core"
mandatory = true
# 须包含 1.0-SNAPSHOT：Maven 下 [1.0,) 不包含 SNAPSHOT，会导致开发环境依赖校验失败
versionRange = "[0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "geckolib"
mandatory = true
versionRange = "${geckolib_version_range}"
ordering = "NONE"
side = "BOTH"

# 玉 Jade：可选，仅客户端；用于扫地机器人生命值等 HUD。
[[dependencies."${mod_id}"]]
modId = "jade"
mandatory = false
versionRange = "[11.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "fantasy_furniture.mixins.json"
